name: End-to-end tests 🧪

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Atualizado para v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Atualizado para v3
        with:
          node-version: '20'  # Especificando Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4  # Atualizado para v4
        with:
          build: npm run build
          start: npm start

      - name: Debug NPM and Node.js version
        run: |
          node -v
          npm -v

      - name: Run Cypress tests directly
        run: npx cypress run